version: '3'
services:
  zabbix-mysql:
   image: mysql:5.7.30
   command: mysqld --character-set-server=utf8 --collation-server=utf8_bin
   container_name: zabbix-mysql
   ports:
   - '3306:3306'
   environment:
       MYSQL_ROOT_PASSWORD: zabbix
   volumes:
       - ./mysql-data:/var/lib/mysql
  zabbix-server:
   image: zabbix/zabbix-server-mysql:latest
   container_name: zabbix-server
   environment:
       DB_SERVER_HOST: "zabbix-mysql"
       MYSQL_USER: root
       MYSQL_PASSWORD: zabbix
   ports:
   - '10051:10051'
   links:
       - zabbix-mysql
   depends_on:
       - zabbix-mysql
  zabbix-web:
     image: zabbix/zabbix-web-nginx-mysql:latest
     container_name: zabbix-web
     environment:
       DB_SERVER_HOST: zabbix-mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: zabbix
       ZBX_SERVER_HOST: "zabbix-server"
       PHP_TZ: Europe/Kiev
     ports:
       - '80:8080'
       - '443:443'
     links:
       - zabbix-mysql
       - zabbix-server
     depends_on:
       - zabbix-mysql
       - zabbix-server
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
    - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
    ports:
    - 9200:9200
  logstach:
    image: docker.elastic.co/logstash/logstash:7.7.0
    links:
    - elasticsearch
    ports:
    - 5044:5044
    depends_on:
    - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
    - 5601:5601
    links:
    - elasticsearch
    depends_on:
    - elasticsearch