version: "3"
services:
  zabbix:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
    - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
    ports:
    - 9200:9200
  logstach:
    image: docker.elastic.co/logstash/logstash:7.7.0
    links:
    - elasticsearch
    ports:
    - 5044:5044
    depends_on:
    - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
    - 5601:5601
    links:
    - elasticsearch
    depends_on:
    - elasticsearch